# Codemagic YAML Configuration for iOS Build
# Bu dosya repository root'unda (Ome klasöründe)
# Eğer repository root'u Ome klasörü ise bu yaml'ı kullanın

workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: |
          cd omechat_app
          flutter pub get
      - name: Build iOS
        script: |
          cd omechat_app
          flutter build ipa --release
    artifacts:
      - omechat_app/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: false
