# Codemagic YAML Configuration for iOS Build
# Bu dosya omechat_app klasörü içinde olduğu için doğrudan çalışır
# Eğer repository root'u üst klasör ise, Codemagic UI'da Working directory: "omechat_app" ayarlayın

workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: false
